<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Alicia Ireland" />
    <meta name="description" content="Welcome to my Life">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title> Willingness to Pay for the Preservation of the Kakadu National Park</title>
    <meta name="generator" content="Hugo 0.61.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/"> Willingness to Pay for the Preservation of the Kakadu National Park</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p><em>I chose the Willingness to Pay for the Preservation of the Kakadu National Park dataset which is from a a survey collected in australia about locals and their opinions on forest conservation. The varibales I chose to analyze include basic demographic information such as age,income,and years of schooling. I was interested in how these demographics would effect/relate to the response varibales such as wildlife (believe it’s important to have places where wildlife is preserved),moreparks (there should be more national parks created from state forests),aboriginal(in deciding how to use areas such as Kakadu national park, their importance to the local aboriginal people should be a major factor) and jobs (jobs are the most important thing in deciding how to use our natural resources). Each of these response variables were rated on a numeric scale from one to five with 1 being dont agree and 5 being strongly agree. Furthermore, my two binary variables, scaled on a yes/no rating, were conservation (if the respondent is member of a conservation organization) and envcon (if the respondent participates in an environmentally friendly lifestlye).</em></p>
<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
</div>
<div id="including-plots" class="section level2">
<h2>Including Plots</h2>
<pre class="r"><code>forest$jobs &lt;- as.factor(forest$jobs)
man1&lt;-manova(cbind(wildlife,moreparks)~answer, data=forest)
summary(man1)</code></pre>
<pre><code>##             Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## answer       2 0.15617   77.246      4   3648 &lt; 2.2e-16 ***
## Residuals 1824                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response wildlife :
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## answer         2  40.60 20.3020  50.356 &lt; 2.2e-16 ***
## Residuals   1824 735.38  0.4032                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response moreparks :
##               Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## answer         2  370.38 185.191  141.97 &lt; 2.2e-16 ***
## Residuals   1824 2379.22   1.304                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code> pairwise.t.test(forest$wildlife,forest$answer,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  forest$wildlife and forest$answer 
## 
##    nn      ny   
## ny 1.9e-07 -    
## yy &lt; 2e-16 0.039
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code> pairwise.t.test(forest$moreparks,forest$answer,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  forest$moreparks and forest$answer 
## 
##    nn      ny     
## ny &lt; 2e-16 -      
## yy &lt; 2e-16 0.00036
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>(.05/9)</code></pre>
<pre><code>## [1] 0.005555556</code></pre>
<pre class="r"><code> 1-.95^9 </code></pre>
<pre><code>## [1] 0.3697506</code></pre>
<pre class="r"><code> covmats&lt;-forest%&gt;%group_by(answer)%&gt;%do(covs=cov(.[2:3]))
for(i in 1:3){print(covmats$covs[i])}</code></pre>
<pre><code>## [[1]]
##       lower    upper
## lower     0   0.0000
## upper     0 382.7651
## 
## [[1]]
##          lower    upper
## lower 1242.226 2986.411
## upper 2986.411 7325.950
## 
## [[1]]
##          lower upper
## lower 6247.132     0
## upper    0.000     0</code></pre>
<pre class="r"><code> ggplot(forest, aes(x = wildlife, y = moreparks)) +
  geom_point(alpha = .5) + geom_density_2d(h=2) + coord_fixed() + facet_wrap(~answer)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-1-1.png" width="672" />
<em>Overall I performed 1 MANOVA, 2 ANOVAs, and 6 t tests (9 total test) making the probability that there is at least one type I error if left unadjusted is .37. To correct this, the significance level was adjusted to .0056 using the bonferroni correction (.05/9). A one-way multivariate analysis of variance (MANOVA) was conducted to determine the effect of the respondents willingness to preserve the park (nn,yy,ny) on the two dependent variables (wildlife and moreparks). Significant differences were found among the three answers on the two dependent measures (Pillae trace= .16,F(4,3648)= 77.246, p&lt;.001). To followup the MANOVA, two Univariate analyses of variance (ANOVAs) for each dependent variable were conducted using the Bonferroni method. The univariate ANOVAs for Wildlife and moreparks were also significant, F(2,40)=50.36, p&lt;.001 , and F(2,370),p&lt;.001, respectively.Post hoc analysis was performed conducting pairwise comparisons to determine which answer differed in wildlife and moreparks.After adjusting for multiple comparisons (bonferroni), all three response answers were found to differ significantly from each other in terms of wildlife and moreparks except for the ny and yy repsonse groups in terms of wildlife (p=.039) . Howere when considering the assumptions, a MANOA test was not consideres to be an appropraite analysis technique. Examination of bivariate density plots for each group revealed that there are deparures from multivariate normality. Additionally,further examination of covariance matricies for each group revealed that the homogeneity of within-group covariance matrices expectation was also not met. </em></p>
<pre class="r"><code>forest%&gt;%dplyr::group_by(conservation)%&gt;%
 dplyr:: summarize(means=mean(income))%&gt;%dplyr::summarize(&quot;mean_diff:&quot;=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean_diff:`
##          &lt;dbl&gt;
## 1         6.47</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
newz&lt;-data.frame(income=sample(forest$income),conservation=forest$conservation)
rand_dist[i]&lt;-mean(newz[newz$conservation==&quot;yes&quot;,]$income)-
              mean(newz[newz$conservation==&quot;no&quot;,]$income)}
mean(rand_dist&gt;6.47)*2</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = 6.47,col=&quot;red&quot;)}</code></pre>
<p><img src="/Project2_files/figure-html/cars-1.png" width="672" /></p>
<pre class="r"><code> t.test(data=forest,income~conservation)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  income by conservation
## t = -3.6425, df = 130.33, p-value = 0.0003884
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -9.984824 -2.956215
## sample estimates:
##  mean in group no mean in group yes 
##          21.23536          27.70588</code></pre>
<p><em>The null hypothesis is that the mean income is the same for respondents that are active conservationist vs.those who are non active consevationist. Thus, the alterante hypothesis is that the mean income is different for those who are active conservationist vs. non-active consevationist. After performing the randomization test, it was found that there is 0 probability of observing a mean difference as extreme as the one we got under the randomization distributions.</em></p>
<p>You can also embed plots, for example:</p>
<pre class="r"><code>forest$school_c= forest$schooling-mean(forest$schooling)
fitz&lt;-lm(income ~ answer * moreparks, data=forest)
summary(fitz)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ answer * moreparks, data = forest)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.993 -12.393  -3.298   5.814  80.814 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         25.2930     1.7356  14.573  &lt; 2e-16 ***
## answerny            -5.8266     3.8784  -1.502  0.13319    
## answeryy            -2.4225     2.9412  -0.824  0.41024    
## moreparks           -1.2999     0.4946  -2.628  0.00865 ** 
## answerny:moreparks   1.2439     0.9747   1.276  0.20204    
## answeryy:moreparks   1.2698     0.7365   1.724  0.08488 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.38 on 1821 degrees of freedom
## Multiple R-squared:  0.009697,   Adjusted R-squared:  0.006978 
## F-statistic: 3.566 on 5 and 1821 DF,  p-value: 0.003264</code></pre>
<pre class="r"><code>resids&lt;-fitz$residuals; fitvals&lt;-fitz$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/pressur-1.png" width="672" /></p>
<pre class="r"><code> ggplot()+geom_histogram(aes(resids),bins=20)</code></pre>
<p><img src="/Project2_files/figure-html/pressur-2.png" width="672" /></p>
<pre class="r"><code> ggplot()+geom_qq(aes(sample=resids))+geom_qq_line(aes(sample=resids),color=&#39;red&#39;)</code></pre>
<p><img src="/Project2_files/figure-html/pressur-3.png" width="672" /></p>
<pre class="r"><code> summary(fitz)$coef[,1:2]</code></pre>
<pre><code>##                     Estimate Std. Error
## (Intercept)        25.292987  1.7355734
## answerny           -5.826622  3.8784329
## answeryy           -2.422517  2.9411734
## moreparks          -1.299917  0.4945849
## answerny:moreparks  1.243923  0.9746917
## answeryy:moreparks  1.269806  0.7365454</code></pre>
<pre class="r"><code> library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code> library(sandwich)
coeftest(fitz, vcov=vcovHC(fitz))[,1:2]</code></pre>
<pre><code>##                     Estimate Std. Error
## (Intercept)        25.292987  1.9690422
## answerny           -5.826622  3.5816576
## answeryy           -2.422517  3.1247149
## moreparks          -1.299917  0.5287024
## answerny:moreparks  1.243923  0.9319516
## answeryy:moreparks  1.269806  0.7669568</code></pre>
<pre class="r"><code> (sum((forest$income-mean(forest$income))^2)-sum(fitz$residuals^2))/sum((forest$income-mean(forest$income))^2)</code></pre>
<pre><code>## [1] 0.009697233</code></pre>
<pre class="r"><code>fit2&lt;-lm(income ~ answer + moreparks, data=forest)
summary(fit2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ answer + moreparks, data = forest)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -21.751 -12.229  -3.989   5.771  81.400 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  23.0888     1.2762  18.092   &lt;2e-16 ***
## answerny     -1.3888     1.2111  -1.147   0.2516    
## answeryy      2.2822     0.9164   2.490   0.0128 *  
## moreparks    -0.6200     0.3360  -1.845   0.0652 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.39 on 1823 degrees of freedom
## Multiple R-squared:  0.007789,   Adjusted R-squared:  0.006156 
## F-statistic:  4.77 on 3 and 1823 DF,  p-value: 0.002573</code></pre>
<pre class="r"><code>qplot(x = moreparks, y = income, color = answer, data = forest) +
  stat_smooth(method = &quot;lm&quot;, se = FALSE, fullrange = TRUE)</code></pre>
<p><img src="/Project2_files/figure-html/pressur-4.png" width="672" /></p>
<pre class="r"><code> anova(fitz,fit2,test=&quot;LRT&quot;)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: income ~ answer * moreparks
## Model 2: income ~ answer + moreparks
##   Res.Df    RSS Df Sum of Sq Pr(&gt;Chi)
## 1   1821 488855                      
## 2   1823 489797 -2   -941.99    0.173</code></pre>
<p><em>Interperting the coefficient estimates it is seen that respondents who answered maybe(ny) in willingness to donate tended to have a lower income(b1=-5.8) than those who answered yes(yy)(b2=-2.4). Furthermore the people who were not willing to donate but greater supported that there should be more national parks created from state forests tended to have a lower income (b3=-1.3). However those who answere ny or yy to willingness to donate and who also agreed strongly that theire shoule be more parks tended to have a higher income (b4=1.2 and b5=1.3).However, when checking assumptions of linearity, normality, and homoskedasticity it is evident from the graph that these expectations are not met. When further recomputing the regression results with robust standard errors the significance did not change and their was only a slight increase in the std. errors overall. .0096 of the variation in the outcome is explain by the model. Additionally,When rerunning the regression without interactions and comparing it with the interaction model using a likelihood ratio test it is apparent that the smaller residual deviance of the interaction model is better.</em></p>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-boot_dat&lt;-forest[sample(nrow(forest),replace=TRUE),]
  fit&lt;-lm(income ~ answer * moreparks, data=boot_dat)
  coef(fit)
})
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) answerny answeryy moreparks answerny:moreparks answeryy:moreparks
## 1    1.956779 3.548774 3.067197 0.5273782          0.9294793           0.754877</code></pre>
<p><em>Compared to the original SEs and the robust SEs,the bootstrapped SEs for all the variables were about the same.Overall the bootstrapped SE’s tended to be slighlty lower than the robust SE’s and slightly higher than the original SE’s.</em></p>
<pre class="r"><code>forest1=forest %&gt;% dplyr::mutate(envcon = ifelse(envcon == &quot;no&quot;,0,1))
forest1$income_c= forest1$income-mean(forest$income)
forest1$age_c= forest1$age-mean(forest1$age)
fit4&lt;-glm(envcon ~ age_c + income_c,data=forest1,family=&quot;binomial&quot;)
summary(fit4)</code></pre>
<pre><code>## 
## Call:
## glm(formula = envcon ~ age_c + income_c, family = &quot;binomial&quot;, 
##     data = forest1)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.501  -1.251   1.024   1.094   1.228  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.180099   0.047139   3.821 0.000133 ***
## age_c       -0.006520   0.002766  -2.358 0.018395 *  
## income_c     0.006592   0.002932   2.248 0.024586 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2518.2  on 1826  degrees of freedom
## Residual deviance: 2506.1  on 1824  degrees of freedom
## AIC: 2512.1
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>forest1$logit&lt;-predict(fit4) #get predicted log-odds
forest1$envcon&lt;-factor(forest$envcon,levels=c(&quot;yes&quot;,&quot;no&quot;))
library(ggplot2)
library(MASS)</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<pre class="r"><code>head(forest1)</code></pre>
<pre><code>##   X lower upper answer recparks jobs lowrisk wildlife future aboriginal finben
## 1 1     0     2     nn        3    1       5        5      1          1      1
## 2 2     0     2     nn        5    5       3        5      5          1      5
## 3 3     0     2     nn        4    4       5        3      5          1      5
## 4 4     0     2     nn        1    2       4        5      3          4      3
## 5 5     0     2     nn        2    4       5        3      1          3      4
## 6 6     0     2     nn        3    3       3        4      5          2      3
##   mineparks moreparks gov envcon vparks tvenv conservation    sex age schooling
## 1         4         5   1    yes    yes     1           no   male  27         3
## 2         1         5   2     no    yes     3           no female  32         4
## 3         3         2   2     no    yes     2           no   male  32         4
## 4         3         5   1    yes     no     1          yes female  70         6
## 5         1         1   1     no    yes     3           no   male  32         5
## 6         4         3   1    yes    yes     1           no   male  47         6
##   income major   school_c   income_c      age_c      logit
## 1     25    no -0.6836344   3.343186 -15.968254 0.30625700
## 2      9    no  0.3163656 -12.656814 -10.968254 0.16818725
## 3     25   yes  0.3163656   3.343186 -10.968254 0.27365461
## 4     25    no  2.3163656   3.343186  27.031746 0.02587642
## 5     35   yes  1.3163656  13.343186 -10.968254 0.33957171
## 6     27    no  2.3163656   5.343186   4.031746 0.18903085</code></pre>
<pre class="r"><code>ggplot(forest1,aes(logit, fill=envcon))+geom_density(alpha=.3)+geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="/Project2_files/figure-html/pre-1.png" width="672" /></p>
<pre class="r"><code>prob&lt;-predict(fit4,type=&quot;response&quot;) #get predictions for every student in the dataset
pred&lt;-ifelse(prob&gt;.5,1,0)
table(truth=forest1$envcon, prediction=pred)%&gt;%addmargins</code></pre>
<pre><code>##      prediction
## truth    0    1  Sum
##   yes  157  838  995
##   no   201  631  832
##   Sum  358 1469 1827</code></pre>
<pre class="r"><code>(201+838)/1827 #accuracy</code></pre>
<pre><code>## [1] 0.5686918</code></pre>
<pre class="r"><code>838/1469 #sensitivity</code></pre>
<pre><code>## [1] 0.5704561</code></pre>
<pre class="r"><code>201/358 #specicifity</code></pre>
<pre><code>## [1] 0.5614525</code></pre>
<pre class="r"><code>838/995#PPV</code></pre>
<pre><code>## [1] 0.8422111</code></pre>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(forest1)+geom_roc(aes(d=envcon,m=prob), n.cuts=0)+geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2)
ROCplot</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming no = 0 and yes = 1!</code></pre>
<p><img src="/Project2_files/figure-html/pre-2.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming no = 0 and yes = 1!</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5376625</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  data.frame(acc,sens,spec,ppv,auc)
}

set.seed(1234)
k=10 
data1&lt;-forest1[sample(nrow(forest1)),] 
folds&lt;-cut(seq(1:nrow(forest1)),breaks=k,labels=F) 
diags&lt;-NULL
for(i in 1:k){

  forest&lt;-data1[folds!=i,]
  test&lt;-data1[folds==i,]
  truth&lt;-test$envcon
 
  fit5&lt;-glm(envcon~age_c+ income_c,data=forest1,family=&quot;binomial&quot;)
  probs&lt;-predict(fit5,newdata = test,type=&quot;response&quot;)

  diags&lt;-rbind(diags,class_diag(probs,truth))
}

apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.5687083 0.2406947 0.8414931 0.5610932 0.5394689</code></pre>
<pre class="r"><code>exp(.1800990)</code></pre>
<pre><code>## [1] 1.197336</code></pre>
<pre class="r"><code>exp(-0.0065205 )</code></pre>
<pre><code>## [1] 0.9935007</code></pre>
<pre class="r"><code>exp( 0.0065917)</code></pre>
<pre><code>## [1] 1.006613</code></pre>
<p><em>When interpreting coefficient estimates in context it is seen that the intercept of 1.18 is the odds of being a conservationist if the individual has the average income and the average age. Furthermore a 1 year increase in age increases odds by .9935 when controlling for income.When controlling for aage, +1,000$ in income increases odds by 1.007.From the confusion matrix of the logistic regression the following were calculated, the Accuracy (.57), the Sensitivity or the probability of correcty detecting that the respondent is a conservationist (.57), Specificity or the probability of correctly identyfying that they are not a conservationist (.56), and the Recall or the proportion as those classified as conservationist who actually are(.84). Additionally, from the generated ROC curve and calculated AUC (.57) which is bad which indicates that it is hard to predict if someone is an environmental conservative ffrom their age and income.From the 10-fold CV and report the accuracy was .62, the sensitivity was .74, and the recall was .633.</em></p>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 3.0-2</code></pre>
<pre class="r"><code>y&lt;-as.matrix(forest$envcon)
x&lt;-forest%&gt;%dplyr::select(-vparks,-answer,-conservation,-sex,-envcon,-jobs,-major,-envcon)%&gt;%mutate_all(scale)%&gt;%as.matrix
cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)


lasso1&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 21 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)  1.874602e-01
## X            .           
## lower        .           
## upper        1.533894e-01
## recparks     .           
## lowrisk      .           
## wildlife     .           
## future       .           
## aboriginal   8.421993e-02
## finben      -1.667383e-01
## mineparks    .           
## moreparks    .           
## gov          .           
## tvenv        .           
## age          .           
## schooling    9.269469e-02
## income       .           
## school_c     1.439745e-16
## income_c     .           
## age_c        .           
## logit        .</code></pre>
<pre class="r"><code>set.seed(1234)
data1&lt;-forest1[sample(nrow(forest1)),]
folds&lt;-cut(seq(1:nrow(forest1)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
  train&lt;-data1[folds!=i,]
  test&lt;-data1[folds==i,]
  truth&lt;-test$envcon
  fit&lt;-glm(envcon~upper+schooling+aboriginal,data=forest1,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  preds&lt;-ifelse(probs&gt;.5,1,0)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.6240017 0.4865416 0.7391483 0.6123698 0.6532825</code></pre>
<p><em>When running a LASSO regression and inputting all the variables as predictors, the variables are retained were the most important predictors of envcon which were upper, schooling, and aboriginal. After the performing a 10-fold CV using the same model, the accuracy was calculated to be .62 and auc was. 65 which were both improvements from the previous logistic regression test.</em></p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
